/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author CAMILO
 */
public class menu2 extends javax.swing.JFrame {

    /**
     * Creates new form menu2
     */
    public menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        proovedores_btn = new javax.swing.JButton();
        empleados_btn = new javax.swing.JButton();
        empleados_btn1 = new javax.swing.JButton();
        empleados_btn3 = new javax.swing.JButton();
        producto_btn = new javax.swing.JButton();
        factura_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        venta_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        empleados_btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proovedores_btn.setText("PROOVEDORES");
        jPanel1.add(proovedores_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        empleados_btn.setText("Agregar Usuario");
        empleados_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleados_btnActionPerformed(evt);
            }
        });
        jPanel1.add(empleados_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 160, -1));

        empleados_btn1.setText("Cerrar");
        empleados_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleados_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(empleados_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 119, -1));

        empleados_btn3.setText("CLIENTE");
        empleados_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleados_btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(empleados_btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 119, -1));

        producto_btn.setText("PRODUCTOS");
        jPanel1.add(producto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 120, 30));

        factura_btn.setText("FACTURAS");
        jPanel1.add(factura_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/logo poo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 720, 100));

        venta_btn.setText("VENTAS");
        venta_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venta_btnActionPerformed(evt);
            }
        });
        jPanel1.add(venta_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/image/anime-girl-anime-art-silhouette-wallpaper-preview.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 100, 630, 420));

        empleados_btn2.setText("Agregar Usuario");
        empleados_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleados_btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(empleados_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empleados_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleados_btnActionPerformed
       
         usuarios ve = new usuarios();
             ve.setVisible(true);
             this.dispose();
    }//GEN-LAST:event_empleados_btnActionPerformed

    private void venta_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venta_btnActionPerformed

             ventas ventas = new ventas();
             ventas.setVisible(true);
             this.dispose();
      
        
        
    }//GEN-LAST:event_venta_btnActionPerformed

    private void empleados_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleados_btn1ActionPerformed
      login3 ventas = new login3();
             ventas.setVisible(true);
             this.dispose();
    }//GEN-LAST:event_empleados_btn1ActionPerformed

    private void empleados_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleados_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleados_btn2ActionPerformed

    private void empleados_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleados_btn3ActionPerformed
       clientes ventas = new clientes();
             ventas.setVisible(true);
             this.dispose();
      
    }//GEN-LAST:event_empleados_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empleados_btn;
    private javax.swing.JButton empleados_btn1;
    private javax.swing.JButton empleados_btn2;
    private javax.swing.JButton empleados_btn3;
    private javax.swing.JButton factura_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton producto_btn;
    private javax.swing.JButton proovedores_btn;
    private javax.swing.JButton venta_btn;
    // End of variables declaration//GEN-END:variables
}
